### ISSUE TITLE
Output file naming mitch_report()

### ISSUE THREAD

**Issue by HeyLifeHD** [markziemann/mitch#10]
Dear Mark,

I think there is a minor problem with the mitch_report() function. When trying to specify the output file path of the html report it is appending the path to the working directory. i think this should be avoided when specifying absolute paths. 
```
 HTMLNAME <- paste(getwd(), HTMLNAME, sep = "/")
````

Best regards,

Joschka

**Comment by HeyLifeHD** [comment]
Thanks, it seems to be working now. 

A completely independent question:
Do you have any recommendations on how to integrate differentially methylated regions with expression data? For DMRs we normally work with methylation differences instead of log2 fold changes and dont have a  p-value for region-based analysis. I am currently unsure on how to pre-rank the lists.

Thanks a lot!

**Comment by markziemann** [comment]
Thanks for looking into that Joschka. I have just pushed to release so the changes will be propagated to bioconductor users in the next 24 hrs.

Regarding your quesiton about integrative methylation gene set analysis, there are many ways to do this and none are perfect because methylation is based on CpG sites and pathway analysis is based on gene identifiers. There need to be some simplifying assumptions made and these generally lead to loss of information as CpG based data is summarised to gene IDs.

Previously, when I was working with methylation data and doing integrative pathway analysis with expression data, we were doing MeDIP and MBD-seq. We would define the promoter as -3000 to +1000 bp around the TSS and count the number of reads that mapped there, which we would feed into edgeR/DESeq2. becasue genes can have >1 promoter we would select the promoter with the smallest p-value or largest confident effect size (confect) as representative for that gene. Next, we would use the directional p-value approach ([Rafehi et al 2014](https://pubmed.ncbi.nlm.nih.gov/24732587/)) for scoring genes before GSEA/mitch.

Obviously promoter based analysis misses 90% of CpG sites, but probably captures the methylation changes likely to impact gene expression the most. There are other possibilities, such as summarising the counts for the whole gene, as well as picking the most significant DMR for a gene, but they are somewhat biased methds and the changes in methylation in the gene body may not be directly related to the expression status of that gene. There are many enhancers which are located in introns of other genes.

**Comment by HeyLifeHD** [comment]
Thanks Mark for your detailed response. 
So far I was trying to use mitch by incorporating DMRs with gene expression. For this, I focussed on Promoter DMRs to reduce the complexity and have a one to one match with gene expression. This seems to have worked by picking up interesting gene sets, I already identified in an independent analysis, by effect sizes but not by significance (barely any gene sets reached sign. cutoff). I could imagine, this has something to do with my scoring method (using the combined stat area and difference in methylation for DMRs and stat as well as l2fc for expression). May
The other approach to treat methylation results as count data is new to me and I will take a look at the mentioned paper.

Best,
Joschka
