### ISSUE TITLE
Question on Type I Error

### ISSUE THREAD

**Issue by gabrielodom** [markziemann/mitch#21]
Oh hi Mark,
First of all, thank you so much for your help on Twitter. I'd never heard of this tool, and it turns out to work very well for what we need. For context, we have 71 samples and roughly 2000 genes with recorded copy number aberration, RNAseq, and shotgun proteomics. We are interested in detecting gene sets / pathways that are differentially expressed between tumour v normal samples concurrently across all three platforms.

In order to test this tool before applying it to our real data, we created a few gene sets of our own, and increased the expression levels for some of the samples within a couple of those pathways. We were very happy to find that `mitch::` detected all five pathways for which we synthetically boosted the signal. Here are two screenshots with some results, the first where we set `priority = "effect"`, and the second where we set `priority = "significance"`:

![ranked by effect](https://user-images.githubusercontent.com/24464126/102032125-fbd64380-3d85-11eb-8025-00b93ba48f78.png)
![image](https://user-images.githubusercontent.com/24464126/102032243-3dff8500-3d86-11eb-9648-07c8953cf6a8.png)

As you can see, we are very pleased with the results when we sort the pathways by "effect" rather than just p-value alone. However, we are stuck on the best way to calculate test size / Type I error if we **don't** know a priori how many gene sets should be significant. If we use the "significance" ranking, then the Type I error rate is over 80% in our simulation. If we use "effect", we don't know how many pathways to treat as significant. We did notice that the column `s.dist` was above 1 for all of the treated pathways and less than 1 for the non-treated pathways, so we could create a threshold that way (the issue there is that we don't really know what the `s.dist` column measures or how it's calculated--the help files are a touch sparse in that area).

**Summary**: we like the tool, but we need to know the best technique to measure gene set significance with a well-controlled Type I error rate.

**Comment by markziemann** [comment]
Hi Gabe,
Thanks for doing these analysis, it is indeed quite interesting. Here are my thoughts:

1. According to our randomisation test described in the [mitch paper](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-020-06856-9) (Fig 3) the FDR threshold of 0.01 is more stringent and recommended.

2. Overlap between gene sets could be the reason why there are some false positives in your test. For example in Fig7 of the paper, we randomly selected gene sets, but in real life gene sets there is a lot of overlap between sets. Eg: "ribosome" and "translation"

3. The work shown in figure 8 of the paper suggests that gene sets with s =< 0.08 have inflated p-values, so be wary of those possible false positives.

Priority and significance ranking are both important in the intepretation of these datasets. When there are a lot of sets with FDR<0.01 then it makes sense to focus on the ones with the largest effect size. When there are relatively few FDR<0.01 sets, then it makes sense to focus on the ones with smallest p-values. In future I would like to implement something like [topconfects](https://bioconductor.org/packages/release/bioc/html/topconfects.html) for gene sets.

**Comment by gabrielodom** [comment]
Thank you for your quick reply!

1. That's the column `p.adjustMANOVA`, correct? Using a 0.01 threshold, we still have over 75% of the tested pathways marked as significant (see my response to point 2).
2. You are absolutely correct. To mitigate this overlap, we independently clustered a set of RNAseq data to create 50 gene sets with no overlap. These gene sets range from 10-100 gene symbols in size. Therefore, we are confident that there isn't any "bleed-through" from one gene set to another.
3. The smallest value of `s.dist` is 0.083, so we don't think that's an issue.

I'll attach our .gmt file (`cluster_pathway_collection_20201117.txt`), the data frame of p-values (`test_mitch_input_20201214.xlsx`), and the enrichment result (`test_mitch_out_20201214.xlsx`) of `mitch_calc()` below.

**Comment by gabrielodom** [comment]
The two .xlsx files I converted from .csv because GitHub won't let me upload a .csv file. The .txt file should be a .gmt file for the same reason.

[test_mitch_input_20201214.xlsx](https://github.com/markziemann/mitch/files/5689676/test_mitch_input_20201214.xlsx)
[test_mitch_out_20201214.xlsx](https://github.com/markziemann/mitch/files/5689680/test_mitch_out_20201214.xlsx)
[cluster_pathway_collection_20201117.txt](https://github.com/markziemann/mitch/files/5689696/cluster_pathway_collection_20201117.txt)

**Comment by markziemann** [comment]
I'm wondering how you performed ranking to make the test_mitch_input_20201214.xlsx ?
I ask because you only have values between 0 and 1. For a normal analysis of RNA-seq with DESeq2 there will be up and down regulated genes. There for the mitch input values (DESeq2 test statistics) will have negative and postive values.

From the results you have shown me in test_mitch_out_20201214.xlsx I've got a few other observations:

* mitch does a 2-sided competitive test, so it will find sets with lower as well as higher values in the profile. From what I understand about your simulation, you've made changes to all three omics data in the same direction. Small values in the profile data will be interpreted as downregulation by mitch. But mitch will be searching for gene sets with either down or upregulation just like GSEA does.
* Some of the genesets like cluster24 and cluster37 have extreme values for s.CNV. s values <0.7 or >0.7 are so far from the null (random, near 0) that they will nearly always give FDR<0.05. I think this is the origin of some of the false positives
![image](https://user-images.githubusercontent.com/5591840/102352882-760ffd80-3ffc-11eb-86bc-fbc44c1a24da.png)
* If your simulation modified the values for CNV, Prot and RNAseq towards low values, then consider filtering the results to obtain only the sets that have FDR<0.05 and s value <0 for CNV, Prot and RNAseq.

**Comment by gabrielodom** [comment]
They are single-gene p-values. Is that wrong?
Also, thank you so much for taking the time to help me with this.

**Comment by gabrielodom** [comment]
If I use single-gene "estimates" instead of p-values, do I ignore the level of significance? Or should I use t-statistics instead of p-values, to preserve direction?

**Comment by markziemann** [comment]
Single p-value is not really advisable because it doesn't have directionality. For DESeq2, the test statistic is recommended (and it used by the `mitch_import`) function. If test statistic is not available, then you can calculate it this way:

sign of the log fold change multiplied by the -log10 of the p-value.

The mitch_import() documentation might have additional information for you

**Comment by gabrielodom** [comment]
@markziemann thank you for all the help! I forgot to close this issue ages ago. Sorry!
